import fs from 'fs/promises';
import path from 'path';

// Define the path to the local JSON memory bank
const VAULT_PATH = path.join(process.cwd(), 'src', 'data', 'ghhost_memory.json');

/**
 * Initializes the vault if it doesn't exist
 */
async function ensureVaultExists() {
  try {
    await fs.access(VAULT_PATH);
  } catch (error) {
    // If the file doesn't exist, create it with a basic schema
    const initialSchema = {
      predictions: {}, // Indexed by YYYY-MM-DD
      playerHistory: {} // Indexed by playerId for quick lookup of past Autopsy grades
    };
    await fs.writeFile(VAULT_PATH, JSON.stringify(initialSchema, null, 2), 'utf-8');
  }
}

/**
 * Logs today's generated predictions into the Memory Vault.
 * @param {string} sport 'NBA' or 'MLB'
 * @param {Array} players The player predictions generated by the engine
 */
export async function logPredictionsToVault(sport, players) {
  if (!players || players.length === 0) return;

  await ensureVaultExists();

  try {
    const data = await fs.readFile(VAULT_PATH, 'utf-8');
    const vault = JSON.parse(data);

    // Use local date formatted as YYYY-MM-DD
    const today = new Date().toLocaleDateString('en-CA', { timeZone: 'America/Chicago' });

    if (!vault.predictions[today]) {
      vault.predictions[today] = { NBA: [], MLB: [] };
    }

    // Overwrite today's predictions for this sport to avoid duplicates on refresh
    // Save ALL predictions as requested for the Transparency Window
    const playsToSave = players;
    
    // Minimalist payload to save space
    vault.predictions[today][sport] = playsToSave.map(p => ({
       playerId: p.playerId,
       playerName: p.player,
       opponentAbbr: p.opponentAbbr,
       evaluations: p.evaluations.map(e => ({
          category: e.category,
          call: e.call.includes('OVER') ? 'OVER' : 'UNDER',
          target: e.projectedTarget || e.avg,
          confidence: e.confidence,
          graded: false, // Will be updated by the Autopsy engine tomorrow
          hit: null,
          actualResult: null,
          contextNote: null // Autopsy reasoning
       }))
    }));

    await fs.writeFile(VAULT_PATH, JSON.stringify(vault, null, 2), 'utf-8');
  } catch (error) {
    console.error(`Failed to log ${sport} predictions to Vault:`, error);
  }
}

/**
 * Reads historical performance for a specific player to adjust current confidence scores.
 * @param {string} playerId The ID of the player
 * @param {string} category The stat category (e.g., 'PTS', 'TB')
 * @returns {Object} An object detailing their historical track record (e.g., { hitRate: 0.6, missedAway: 2 })
 */
export async function getPlayerAutopsyHistory(playerId, category) {
  try {
    await ensureVaultExists();
    const data = await fs.readFile(VAULT_PATH, 'utf-8');
    const vault = JSON.parse(data);

    const history = vault.playerHistory[playerId];
    if (!history || !history[category]) {
      return { total: 0, hits: 0, misses: 0, hitRate: null, contextWarnings: [] };
    }

    const catHistory = history[category];
    const hitRate = catHistory.total > 0 ? (catHistory.hits / catHistory.total) : null;

    return {
      total: catHistory.total,
      hits: catHistory.hits,
      misses: catHistory.misses,
      hitRate: hitRate,
      contextWarnings: catHistory.contextWarnings || []
    };
  } catch (error) {
    return { total: 0, hits: 0, misses: 0, hitRate: null, contextWarnings: [] };
  }
}

/**
 * Fetches the entire player history tree from the Vault for fast synchronous lookups.
 */
export async function getFullPlayerHistory() {
  try {
    await ensureVaultExists();
    const data = await fs.readFile(VAULT_PATH, 'utf-8');
    return JSON.parse(data).playerHistory || {};
  } catch (e) {
    return {};
  }
}
