import { PrismaClient } from '@prisma/client';

const globalForPrisma = global;
const prisma = globalForPrisma.prisma || new PrismaClient();
if (process.env.NODE_ENV !== 'production') globalForPrisma.prisma = prisma;

/**
 * Logs today's generated predictions into the Postgres Database.
 * @param {string} sport 'NBA' or 'MLB'
 * @param {Array} players The player predictions generated by the engine
 */
export async function logPredictionsToVault(sport, players) {
  if (!players || players.length === 0) return;

  try {
    // Use local date formatted as YYYY-MM-DD
    const today = new Date().toLocaleDateString('en-CA', { timeZone: 'America/Chicago' });

    const ops = [];
    players.forEach(p => {
      p.evaluations.forEach(e => {
         ops.push({
           dateKey: today,
           sport: sport,
           playerId: String(p.playerId),
           playerName: p.player || p.playerName || 'Unknown',
           teamAbbr: p.team || null,
           opponentAbbr: p.opponentAbbr || null,
           isHome: p.isHome || false,
           category: e.category,
           call: e.call.includes('OVER') ? 'OVER' : 'UNDER',
           target: parseFloat(e.projectedTarget || e.avg || 0),
           confidence: parseInt(e.confidence) || 50,
           graded: false,
           hit: null,
           actualResult: null,
           contextNote: null,
           pitcherHandedness: e.pitcherHand || null
         });
      });
    });

    if (ops.length > 0) {
      await prisma.$transaction([
        prisma.predictionLog.deleteMany({
          where: { dateKey: today, sport: sport, graded: false }
        }),
        prisma.predictionLog.createMany({ data: ops })
      ]);
    }
  } catch (error) {
    console.error(`Failed to log ${sport} predictions to Database:`, error);
  }
}

/**
 * Reads historical performance for a specific player to adjust current confidence scores.
 * @param {string} playerId The ID of the player
 * @param {string} category The stat category (e.g., 'PTS', 'TB')
 * @returns {Object} An object detailing their historical track record (e.g., { hitRate: 0.6, missedAway: 2 })
 */
export async function getPlayerAutopsyHistory(playerId, category) {
  try {
    const history = await prisma.playerHistory.findUnique({
      where: { playerId_category: { playerId: String(playerId), category } }
    });
    if (!history) return { total: 0, hits: 0, misses: 0, hitRate: null, contextWarnings: [] };
    
    return {
      total: history.total,
      hits: history.hits,
      misses: history.misses,
      hitRate: history.hitRate,
      contextWarnings: history.contextWarnings || []
    };
  } catch (error) {
    return { total: 0, hits: 0, misses: 0, hitRate: null, contextWarnings: [] };
  }
}

/**
 * Fetches the entire player history tree from the Database for fast synchronous lookups.
 */
export async function getFullPlayerHistory() {
  try {
    const allHistory = await prisma.playerHistory.findMany();
    const map = {};
    allHistory.forEach(h => {
      if (!map[h.playerId]) map[h.playerId] = {};
      map[h.playerId][h.category] = {
        total: h.total,
        hits: h.hits,
        misses: h.misses,
        hitRate: h.hitRate,
        
        // Over/Under Splitting metrics
        overTotal: h.overTotal || 0,
        overHits: h.overHits || 0,
        overMisses: h.overMisses || 0,
        overHitRate: h.overHitRate || 0,
        
        underTotal: h.underTotal || 0,
        underHits: h.underHits || 0,
        underMisses: h.underMisses || 0,
        underHitRate: h.underHitRate || 0,

        contextWarnings: h.contextWarnings || [],
        homeHits: h.homeHits || 0,
        homeMisses: h.homeMisses || 0,
        awayHits: h.awayHits || 0,
        awayMisses: h.awayMisses || 0,
        opponentSplits: h.opponentSplits || {},
        pitcherHandednessSplits: h.pitcherHandednessSplits || {}
      };
    });
    return map;
  } catch (e) {
    return {};
  }
}

/**
 * Phase 3: Fetches all learned adjustments for a sport as a map.
 * These come from the nightly optimizer's analysis of prediction errors.
 * @param {string} sport 'NBA', 'WNBA', or 'MLB'
 * @returns {Object} Map of bucket → adjustment value (e.g., { "b2b_PTS": -0.03, "home_REB": 0.02 })
 */
export async function getLearnedAdjustments(sport) {
  try {
    const adjustments = await prisma.learnedAdjustment.findMany({
      where: { sport, sampleSize: { gte: 5 } } // Only use adjustments with enough data
    });
    const map = {};
    adjustments.forEach(a => {
      map[a.bucket] = a.adjustment;
    });
    return map;
  } catch (e) {
    return {};
  }
}

/**
 * Phase 8: Fetches all Scouting Notes from the Data Lake for a sport.
 * @param {string} sport 'NBA', 'WNBA', or 'MLB'
 * @returns {Object} Map of playerId -> category -> contextHash -> { note, adjustment, confidence }
 */
export async function getScoutingNotes(sport) {
  try {
    const notes = await prisma.scoutingNote.findMany({
      where: { sport }
    });
    const map = {};
    notes.forEach(n => {
      if (!map[n.playerId]) map[n.playerId] = {};
      if (!map[n.playerId][n.category]) map[n.playerId][n.category] = {};
      map[n.playerId][n.category][n.contextHash] = {
        note: n.note,
        adjustment: n.adjustment,
        confidence: n.confidence
      };
    });
    return map;
  } catch (e) {
    return {};
  }
}

/**
 * Rebuilds the entire PlayerHistory table from scratch using all graded PredictionLogs.
 * Excludes DNPs (hit = null) so hit rates remain 100% true to actual played games.
 */
export async function rebuildPlayerHistoryFromLogs() {
  try {
    const gradedLogs = await prisma.predictionLog.findMany({
      where: { graded: true, hit: { not: null } }
    });

    const map = {};

    for (const log of gradedLogs) {
      const pid = String(log.playerId);
      const cat = log.category;

      if (!map[pid]) map[pid] = {};
      if (!map[pid][cat]) {
        map[pid][cat] = {
          total: 0, hits: 0, misses: 0,
          overTotal: 0, overHits: 0, overMisses: 0,
          underTotal: 0, underHits: 0, underMisses: 0,
          homeHits: 0, homeMisses: 0, awayHits: 0, awayMisses: 0,
          opponentSplits: {}, pitcherHandednessSplits: {}, contextWarnings: []
        };
      }

      const h = map[pid][cat];
      h.total++;

      const isHit = log.hit === true;
      const isOver = log.call === 'OVER';
      const isHome = log.isHome === true;
      const opp = log.opponentAbbr || 'UNK';
      const pHand = log.pitcherHandedness;

      if (!h.opponentSplits[opp]) h.opponentSplits[opp] = { hits: 0, misses: 0 };
      if (pHand && !h.pitcherHandednessSplits[pHand]) {
        h.pitcherHandednessSplits[pHand] = { hits: 0, misses: 0 };
      }

      if (isOver) h.overTotal++;
      else h.underTotal++;

      if (isHit) {
        h.hits++;
        if (isOver) h.overHits++; else h.underHits++;
        if (isHome) h.homeHits++; else h.awayHits++;
        h.opponentSplits[opp].hits++;
        if (pHand && h.pitcherHandednessSplits[pHand]) h.pitcherHandednessSplits[pHand].hits++;
      } else {
        h.misses++;
        if (isOver) h.overMisses++; else h.underMisses++;
        if (isHome) h.homeMisses++; else h.awayMisses++;
        h.opponentSplits[opp].misses++;
        if (pHand && h.pitcherHandednessSplits[pHand]) h.pitcherHandednessSplits[pHand].misses++;
        if (log.contextNote && !log.contextNote.includes('Pure Miss')) {
          if (!h.contextWarnings.includes(log.contextNote)) h.contextWarnings.push(log.contextNote);
        }
      }
    }

    let updatedCount = 0;
    for (const [playerId, categories] of Object.entries(map)) {
      for (const [category, stats] of Object.entries(categories)) {
        const hitRate = stats.total > 0 ? stats.hits / stats.total : 0;
        const overHitRate = stats.overTotal > 0 ? stats.overHits / stats.overTotal : 0;
        const underHitRate = stats.underTotal > 0 ? stats.underHits / stats.underTotal : 0;

        await prisma.playerHistory.upsert({
          where: { playerId_category: { playerId, category } },
          create: {
            playerId, category,
            total: stats.total, hits: stats.hits, misses: stats.misses, hitRate,
            overTotal: stats.overTotal, overHits: stats.overHits, overMisses: stats.overMisses, overHitRate,
            underTotal: stats.underTotal, underHits: stats.underHits, underMisses: stats.underMisses, underHitRate,
            homeHits: stats.homeHits, homeMisses: stats.homeMisses,
            awayHits: stats.awayHits, awayMisses: stats.awayMisses,
            opponentSplits: stats.opponentSplits, pitcherHandednessSplits: stats.pitcherHandednessSplits,
            contextWarnings: stats.contextWarnings
          },
          update: {
            total: stats.total, hits: stats.hits, misses: stats.misses, hitRate,
            overTotal: stats.overTotal, overHits: stats.overHits, overMisses: stats.overMisses, overHitRate,
            underTotal: stats.underTotal, underHits: stats.underHits, underMisses: stats.underMisses, underHitRate,
            homeHits: stats.homeHits, homeMisses: stats.homeMisses,
            awayHits: stats.awayHits, awayMisses: stats.awayMisses,
            opponentSplits: stats.opponentSplits, pitcherHandednessSplits: stats.pitcherHandednessSplits,
            contextWarnings: stats.contextWarnings
          }
        });
        updatedCount++;
      }
    }

    return { success: true, updatedCount };
  } catch (error) {
    console.error('Failed to rebuild player history:', error);
    return { success: false, error: error.message };
  }
}

