import { PrismaClient } from '@prisma/client';

const globalForPrisma = global;
const prisma = globalForPrisma.prisma || new PrismaClient();
if (process.env.NODE_ENV !== 'production') globalForPrisma.prisma = prisma;

/**
 * Logs today's generated predictions into the Postgres Database.
 * @param {string} sport 'NBA' or 'MLB'
 * @param {Array} players The player predictions generated by the engine
 */
export async function logPredictionsToVault(sport, players) {
  if (!players || players.length === 0) return;

  try {
    // Use local date formatted as YYYY-MM-DD
    const today = new Date().toLocaleDateString('en-CA', { timeZone: 'America/Chicago' });

    // Delete existing pending predictions for today/sport to avoid duplicates on refresh
    await prisma.predictionLog.deleteMany({
      where: { dateKey: today, sport: sport, graded: false }
    });

    const ops = [];
    players.forEach(p => {
      p.evaluations.forEach(e => {
         ops.push({
           dateKey: today,
           sport: sport,
           playerId: String(p.playerId),
           playerName: p.player || p.playerName || 'Unknown',
           teamAbbr: p.team || null,
           opponentAbbr: p.opponentAbbr || null,
           isHome: p.isHome || false,
           category: e.category,
           call: e.call.includes('OVER') ? 'OVER' : 'UNDER',
           target: parseFloat(e.projectedTarget || e.avg || 0),
           confidence: parseInt(e.confidence) || 50,
           graded: false,
           hit: null,
           actualResult: null,
           contextNote: null
         });
      });
    });

    if (ops.length > 0) {
      await prisma.predictionLog.createMany({ data: ops });
    }
  } catch (error) {
    console.error(`Failed to log ${sport} predictions to Database:`, error);
  }
}

/**
 * Reads historical performance for a specific player to adjust current confidence scores.
 * @param {string} playerId The ID of the player
 * @param {string} category The stat category (e.g., 'PTS', 'TB')
 * @returns {Object} An object detailing their historical track record (e.g., { hitRate: 0.6, missedAway: 2 })
 */
export async function getPlayerAutopsyHistory(playerId, category) {
  try {
    const history = await prisma.playerHistory.findUnique({
      where: { playerId_category: { playerId: String(playerId), category } }
    });
    if (!history) return { total: 0, hits: 0, misses: 0, hitRate: null, contextWarnings: [] };
    
    return {
      total: history.total,
      hits: history.hits,
      misses: history.misses,
      hitRate: history.hitRate,
      contextWarnings: history.contextWarnings || []
    };
  } catch (error) {
    return { total: 0, hits: 0, misses: 0, hitRate: null, contextWarnings: [] };
  }
}

/**
 * Fetches the entire player history tree from the Database for fast synchronous lookups.
 */
export async function getFullPlayerHistory() {
  try {
    const allHistory = await prisma.playerHistory.findMany();
    const map = {};
    allHistory.forEach(h => {
      if (!map[h.playerId]) map[h.playerId] = {};
      map[h.playerId][h.category] = {
        total: h.total,
        hits: h.hits,
        misses: h.misses,
        hitRate: h.hitRate,
        contextWarnings: h.contextWarnings || [],
        homeHits: h.homeHits || 0,
        homeMisses: h.homeMisses || 0,
        awayHits: h.awayHits || 0,
        awayMisses: h.awayMisses || 0,
        opponentSplits: h.opponentSplits || {}
      };
    });
    return map;
  } catch (e) {
    return {};
  }
}

/**
 * Phase 3: Fetches all learned adjustments for a sport as a map.
 * These come from the nightly optimizer's analysis of prediction errors.
 * @param {string} sport 'NBA', 'WNBA', or 'MLB'
 * @returns {Object} Map of bucket → adjustment value (e.g., { "b2b_PTS": -0.03, "home_REB": 0.02 })
 */
export async function getLearnedAdjustments(sport) {
  try {
    const adjustments = await prisma.learnedAdjustment.findMany({
      where: { sport, sampleSize: { gte: 5 } } // Only use adjustments with enough data
    });
    const map = {};
    adjustments.forEach(a => {
      map[a.bucket] = a.adjustment;
    });
    return map;
  } catch (e) {
    return {};
  }
}
