"use client";
import React, { useState } from 'react';
import { createPortal } from 'react-dom';
import { generateNarrative } from '@/engines/shared/narrativeEngine';
import { Ghost, Sparkles, Lock } from 'lucide-react';
import { usePro } from '@/context/ProContext';

export default function ExplainerCard({ children, prediction, sport, forceLock = false, overlayMode = false, triggerType = 'wrap' }) {
  const [flipped, setFlipped] = useState(false);
  const { isPro } = usePro();

  // If forceLock is true, or if not Pro, we show the lock screen on the back
  const isLocked = forceLock || !isPro;

  const narrative = generateNarrative(prediction, sport);

  const handleFlip = (e) => {
    e.stopPropagation();
    // Prevent flip if clicking on a link or button inside the card (unless it's our own icon trigger)
    if (triggerType === 'wrap' && (e.target.tagName === 'A' || e.target.tagName === 'BUTTON' || e.target.closest('button') || e.target.closest('a'))) {
       return;
    }
    setFlipped(!flipped);
  };

  const narrativeContent = (
    <>
      <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '15px', borderBottom: '1px solid rgba(255,255,255,0.1)', paddingBottom: '12px' }}>
         <Sparkles size={18} color="#a855f7" />
         <h3 style={{ margin: 0, fontSize: '1.1rem', color: '#c084fc', fontWeight: 800 }}>Ghhost Brain Analysis</h3>
      </div>

      {isLocked ? (
         <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', flex: 1, textAlign: 'center', gap: '15px' }}>
            <Lock size={32} color="#f472b6" />
            <div>
               <h4 style={{ margin: '0 0 5px', color: 'white', fontSize: '1.1rem' }}>AI Insights Locked</h4>
               <p style={{ margin: 0, fontSize: '0.85rem', color: 'var(--text-muted)' }}>Upgrade to Pro to view the engine's detailed reasoning.</p>
            </div>
            <button style={{
               background: 'linear-gradient(135deg, #ec4899, #a855f7)',
               border: 'none', padding: '8px 20px', borderRadius: '20px',
               color: 'white', fontWeight: 'bold', cursor: 'pointer',
               marginTop: '5px'
            }}>
               Upgrade to Pro
            </button>
         </div>
      ) : (
         <div style={{ flex: 1, display: 'flex', flexDirection: 'column' }}>
            <p style={{ 
               fontSize: '0.95rem', 
               lineHeight: '1.6', 
               color: 'rgba(255,255,255,0.9)', 
               margin: '0 0 15px 0' 
            }}>
               {narrative}
            </p>
            
            <div style={{ marginTop: 'auto', display: 'flex', alignItems: 'center', gap: '6px', fontSize: '0.75rem', color: 'var(--text-muted)', background: 'rgba(0,0,0,0.3)', padding: '8px 12px', borderRadius: '8px' }}>
               <Ghost size={14} color="#a855f7" />
               <span>Generated by Ghhost Memory Engine</span>
            </div>
         </div>
      )}
    </>
  );

  if (overlayMode) {
    return (
      <>
        {triggerType === 'icon' ? (
           <button 
             onClick={handleFlip} 
             style={{ 
               background: 'rgba(168, 85, 247, 0.15)', 
               border: '1px solid rgba(168, 85, 247, 0.3)', 
               borderRadius: '50%', 
               width: '22px', 
               height: '22px', 
               display: 'flex', 
               alignItems: 'center', 
               justifyContent: 'center', 
               cursor: 'pointer',
               padding: 0
             }}
             title="View AI Insight"
           >
              <Sparkles size={12} color="#a855f7" />
           </button>
        ) : (
           <div onClick={handleFlip} style={{ cursor: 'pointer', height: '100%', width: '100%' }}>
             {children}
           </div>
        )}
        {flipped && typeof document !== 'undefined' && createPortal(
          <div style={{
            position: 'fixed', top: 0, left: 0, width: '100vw', height: '100vh',
            background: 'rgba(0,0,0,0.6)', backdropFilter: 'blur(4px)',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            zIndex: 99999, padding: '20px'
          }} onClick={() => setFlipped(false)}>
            <div style={{
              background: 'linear-gradient(145deg, rgba(30, 27, 75, 0.95), rgba(15, 23, 42, 0.98))',
              borderRadius: '16px', padding: '24px', border: '1px solid rgba(139, 92, 246, 0.3)',
              boxShadow: '0 8px 32px rgba(139, 92, 246, 0.3)', width: '100%', maxWidth: '450px',
              display: 'flex', flexDirection: 'column', minHeight: '300px'
            }} onClick={e => e.stopPropagation()}>
              {narrativeContent}
              <div style={{ textAlign: 'center', marginTop: '20px' }}>
                <span onClick={() => setFlipped(false)} style={{ cursor: 'pointer', fontSize: '0.8rem', color: 'rgba(255,255,255,0.5)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Close</span>
              </div>
            </div>
          </div>,
          document.body
        )}
      </>
    );
  }

  return (
    <div 
      style={{ 
        perspective: '1000px', 
        width: '100%', 
        height: '100%',
        cursor: 'pointer' 
      }}
      onClick={handleFlip}
    >
      <div 
        style={{
          position: 'relative',
          width: '100%',
          height: '100%',
          transition: 'transform 0.6s cubic-bezier(0.4, 0, 0.2, 1)',
          transformStyle: 'preserve-3d',
          transform: flipped ? 'rotateY(180deg)' : 'rotateY(0deg)',
        }}
      >
        {/* FRONT */}
        <div style={{
          position: 'relative', // Need to make this static size context, but we want it to define the height
          width: '100%',
          height: '100%',
          backfaceVisibility: 'hidden',
          WebkitBackfaceVisibility: 'hidden',
        }}>
          {children}
        </div>

        {/* BACK (AI Narrative) */}
        <div style={{
          position: 'absolute',
          top: 0,
          left: 0,
          width: '100%',
          height: '100%',
          backfaceVisibility: 'hidden',
          WebkitBackfaceVisibility: 'hidden',
          transform: 'rotateY(180deg)',
          background: 'linear-gradient(145deg, rgba(30, 27, 75, 0.95), rgba(15, 23, 42, 0.98))',
          borderRadius: '16px',
          padding: '20px',
          border: '1px solid rgba(139, 92, 246, 0.3)',
          boxShadow: '0 8px 32px rgba(139, 92, 246, 0.15)',
          display: 'flex',
          flexDirection: 'column',
          overflowY: 'auto',
          zIndex: 10
        }}>
          {narrativeContent}
          <div style={{ textAlign: 'center', marginTop: '10px' }}>
             <span style={{ fontSize: '0.7rem', color: 'rgba(255,255,255,0.3)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Tap to flip back</span>
          </div>
        </div>
      </div>
    </div>
  );
}
